name: GitHub Pages
on: [ push, workflow_dispatch ]
jobs:
    build-and-publish:
        name: Build and publish
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
                node-version: 18
          - run: npm i
          - run: npm run build
          - uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist
